// <auto-generated />
using System;
using GradeManagementData.Concrete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GradeManagementData.EntityFramework.Concrete.Context.Migrations
{
    [DbContext(typeof(GradeManageDbContext))]
    partial class GradeManageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GradeManagementModel.Concrete.StudentGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Final")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MidTerm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StudentGrades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76c31a19-2262-4765-b7fc-2b7f55734a97"),
                            Final = 35,
                            FirstName = "Stevie",
                            LastName = "Wonder",
                            MidTerm = 42
                        },
                        new
                        {
                            Id = new Guid("2fc5eb80-8aa2-45f2-b01b-e378e474a702"),
                            Final = 45,
                            FirstName = "David",
                            LastName = "Bowie",
                            MidTerm = 45
                        },
                        new
                        {
                            Id = new Guid("b8b7e13f-8e0d-456e-aaec-f2fc26a54e4c"),
                            Final = 83,
                            FirstName = "Robert",
                            LastName = "Plant",
                            MidTerm = 70
                        },
                        new
                        {
                            Id = new Guid("e1782faf-6d29-46be-9d0a-813166ced636"),
                            Final = 95,
                            FirstName = "Elton",
                            LastName = "John",
                            MidTerm = 90
                        },
                        new
                        {
                            Id = new Guid("8f2f2192-72cf-41ee-a06f-4c426db21ec8"),
                            Final = 99,
                            FirstName = "Bob",
                            LastName = "Marley",
                            MidTerm = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
