// <auto-generated />
using GradeManagementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GradeManagementApi.Data.Migrations
{
    [DbContext(typeof(GradeManageDbContext))]
    [Migration("20220516183138_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GradeManagementApi.Data.StudentGrades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Final")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MidTerm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StudentGrades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Final = 35,
                            FirstName = "Stevie",
                            LastName = "Wonder",
                            MidTerm = 42
                        },
                        new
                        {
                            Id = 2,
                            Final = 45,
                            FirstName = "David",
                            LastName = "Bowie",
                            MidTerm = 45
                        },
                        new
                        {
                            Id = 3,
                            Final = 83,
                            FirstName = "Robert",
                            LastName = "Plant",
                            MidTerm = 70
                        },
                        new
                        {
                            Id = 4,
                            Final = 95,
                            FirstName = "Elton",
                            LastName = "John",
                            MidTerm = 90
                        },
                        new
                        {
                            Id = 5,
                            Final = 99,
                            FirstName = "Bob",
                            LastName = "Marley",
                            MidTerm = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
